# Generated by Django 5.0.3 on 2024-08-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_applicantexperince_applicant_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantexperince',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
