# Generated by Django 5.0.3 on 2024-08-29 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_applicantexperince_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_certificate',
            name='applicant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_id', to='myapp.applicantexperince'),
        ),
    ]
